# Linear algebra essentials using Numpy

### Linear algebra essentials

###### Numpy is a powerful tool to work on vectors and matrices.  Also  Linear algebra is one the most essential mathematical skill to have inorder to get more from vectors and matrices, One of them being modeling ML algorithms and optimizing for better performance. 
    • 1. Transpose of a Matrix
    • 2. Inverse of matrix
    • 3. Determinant of matrix
    • 4. Rank of matrix
    • 5. Finding Diagonal elements of matrix
    • 6. Eigen value and Eigen vectors
    • 7. Solving a linear equation

In [1]:
import jovian

In [4]:
import numpy as np

In [2]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "anand815353/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/anand815353/numpy-array-operations


'https://jovian.ml/anand815353/numpy-array-operations'

##### Array creation and resahping 

In [5]:
np.random.seed(0) #seed sets a value so that same random no is genrated each time code runs
arr1 = np.random.randint(90, size=18) 
arr1

array([44, 47, 64, 67, 67,  9, 83, 21, 36, 87, 70, 88, 88, 12, 58, 65, 39,
       87])

In [6]:
arr1=arr1.reshape(3,6)   #resahping array to 2-D matrix of dimension 3x6
arr1

array([[44, 47, 64, 67, 67,  9],
       [83, 21, 36, 87, 70, 88],
       [88, 12, 58, 65, 39, 87]])

## 1. [Transpose of a Matrix](https://www.mathsisfun.com/definitions/transpose-matrix-.html) <--click link to know more about Transpose of matrix
#### To transpose an array we can attach T in caps to the array

In [12]:
arr1.T      # Flips matrix with axis being Diagional

array([[44, 83, 88],
       [47, 21, 12],
       [64, 36, 58],
       [67, 87, 65],
       [67, 70, 39],
       [ 9, 88, 87]])

#### also we can do the same with np.transpose()

In [18]:
np.transpose(arr1)

array([[44, 83, 88],
       [47, 21, 12],
       [64, 36, 58],
       [67, 87, 65],
       [67, 70, 39],
       [ 9, 88, 87]])

#### on 3-D matrix

In [20]:
arr1=arr1.reshape(2,3,3)  #rehaping matrix to dimension 2x3x3 
arr1

array([[[44, 47, 64],
        [67, 67,  9],
        [83, 21, 36]],

       [[87, 70, 88],
        [88, 12, 58],
        [65, 39, 87]]])

In [35]:
np.transpose(arr1,(0,1,2))  #3-axis so 0,1,2 .... no change!

array([[[44, 47, 64],
        [67, 67,  9],
        [83, 21, 36]],

       [[87, 70, 88],
        [88, 12, 58],
        [65, 39, 87]]])

#### no change therefore we can assume  
    • 0 -> is z-axis,  
    • 1 -> is x-axis,  
    • 2 -> is y-axis

In [31]:
np.transpose(arr1,(0,2,1)) #replaces elements in Y-axis with X-axis

array([[[44, 67, 83],
        [47, 67, 21],
        [64,  9, 36]],

       [[87, 88, 65],
        [70, 12, 39],
        [88, 58, 87]]])

In [30]:
np.transpose(arr1,(2,1,0)) # replace elements in Z-axis with Y-axis

array([[[44, 87],
        [67, 88],
        [83, 65]],

       [[47, 70],
        [67, 12],
        [21, 39]],

       [[64, 88],
        [ 9, 58],
        [36, 87]]])

## 2. [Inverse of matrix](https://www.mathsisfun.com/algebra/matrix-inverse.html)<--click link to know more

In [36]:
np.linalg.inv(arr1)

array([[[-0.00902562,  0.00141292,  0.01569231],
        [ 0.00676008,  0.01513607, -0.01580193],
        [ 0.01686568, -0.01208693,  0.00081608]],

       [[ 0.00842265,  0.01838047, -0.02077311],
        [ 0.02687228, -0.01278611, -0.01865708],
        [-0.01833898, -0.00800083,  0.03537791]]])

In [37]:
arr1=arr1.reshape(3,6)   #resahping to dimension 3x6
arr1

array([[44, 47, 64, 67, 67,  9],
       [83, 21, 36, 87, 70, 88],
       [88, 12, 58, 65, 39, 87]])

In [38]:
np.linalg.inv(arr1)      # error because trying to find inverse of matrix for non-square matrix.

LinAlgError: Last 2 dimensions of the array must be square

##### error because we trying to find inverse of non-square matrix.

## 3. [Determinant of matrix](https://www.mathsisfun.com/algebra/matrix-determinant.html)<--click link to know more

In [39]:
square_matrix=np.random.randint(90, size=16).reshape(4,4)  #making a new square matrix
square_matrix 

array([[46, 88, 81, 37],
       [25, 77, 72,  9],
       [20, 80, 69, 79],
       [47, 64, 82, 88]])

In [41]:
np.linalg.det(square_matrix)  #Determinant of matrix

-2885761.999999997

##### similar to Inverse of matrix Determinant only exists for Square matrix

In [42]:
np.linalg.det(arr1)  #The determinant only exists for square matrices

LinAlgError: Last 2 dimensions of the array must be square

## 4. [Rank of matrix](https://www.mathsisfun.com/algebra/matrix-rank.html) <-click  link to know more.

#####  The rank is how many of the rows are "unique": not made of other rows or  the columns.
##### When the rank equals the smallest dimension it is called "full rank", a smaller rank is called "rank deficient".

In [43]:
square_matrix

array([[46, 88, 81, 37],
       [25, 77, 72,  9],
       [20, 80, 69, 79],
       [47, 64, 82, 88]])

In [44]:
np.linalg.matrix_rank(square_matrix)

4

In [46]:
arr1

array([[44, 47, 64, 67, 67,  9],
       [83, 21, 36, 87, 70, 88],
       [88, 12, 58, 65, 39, 87]])

In [45]:
np.linalg.matrix_rank(arr1)

3

## 5. Finding diagonal elements of matrix

In [49]:
square_matrix

array([[46, 88, 81, 37],
       [25, 77, 72,  9],
       [20, 80, 69, 79],
       [47, 64, 82, 88]])

In [51]:
square_matrix.diagonal()

array([46, 77, 69, 88])

In [47]:
arr1

array([[44, 47, 64, 67, 67,  9],
       [83, 21, 36, 87, 70, 88],
       [88, 12, 58, 65, 39, 87]])

In [50]:
arr1.diagonal()

array([44, 21, 58])

### Finding elements above and below diagonal

In [52]:
arr1.diagonal(offset=1)  #offset is +ve i.e 1 above diagonal

array([47, 36, 65])

In [71]:
arr1.diagonal(offset=2)  #offset is +ve i.e 2 above diagonal

array([64, 87, 39])

In [53]:
arr1.diagonal(offset=-1)  #offset is -ve i.e 1 below diagonal

array([83, 12])

In [72]:
arr1.diagonal(offset=-2)  #offset is -ve i.e 2 below diagonal

array([88])

## 6. [eigen value and eigen vectors](https://www.mathsisfun.com/algebra/eigenvalue.html)<-click link to know more.

In [54]:
eigen_values ,eigen_vectors=np.linalg.eig(square_matrix)  #returns two values ...1st eigenvalue and 2nd eigenvector

In [55]:
eigen_values

array([234.74908064, -14.89535524,  21.17902806,  38.96724654])

In [56]:
eigen_vectors

array([[-0.50163992,  0.07470063, -0.7436433 , -0.5018447 ],
       [-0.34898997,  0.5703933 , -0.36011553, -0.55144575],
       [-0.51533944, -0.78336776,  0.50662065,  0.39881042],
       [-0.60082331,  0.23538531,  0.24626603,  0.53386303]])

## 7. [solving linear equations](https://www.mathsisfun.com/algebra/systems-linear-equations-matrices.html)<-click link to know more.

##### 4x  + 3y = 20
##### -5x + 9y = 26

### 7.1 solving manually

In [66]:
A = np.array([4,3,-5,9]).reshape(2,2)
A

array([[ 4,  3],
       [-5,  9]])

In [67]:
inv_A = np.linalg.inv(A)
inv_A

array([[ 0.17647059, -0.05882353],
       [ 0.09803922,  0.07843137]])

In [68]:
B = np.array([20, 26])

In [69]:
solved =np.linalg.inv(A).dot(B)
solved

array([2., 4.])

### 7.2 using "np.linalg.solve()"

In [70]:
solved2 = np.linalg.solve(A,B)
solved2

array([2., 4.])

    More Functions in numpy.linalg are listed below.

    
    Matrix and vector products
    --------------------------

       multi_dot
       matrix_power

    Decompositions
    --------------
    
       cholesky
       qr
       svd

    Matrix eigenvalues
    ------------------

       eig
       eigh
       eigvals
       eigvalsh

    Norms and other numbers
    -----------------------

       norm
       cond
       det
       matrix_rank
       slogdet

    Solving equations and inverting matrices
    ----------------------------------------

       solve
       tensorsolve
       lstsq
       inv
       pinv
       tensorinv

    Exceptions
    ----------
    
       LinAlgError