# learning python libraies PART 6
aNAND tIRKEY

In [1]:
import numpy as np
import platform
import matplotlib.pylab as plt
print(platform.python_version())
print(np.__version__)
print(plt.__version__)

3.7.4
1.18.1
1.18.1


##### Statistics is the science of collecting, analyzing, presenting, and interpreting data.

##### Branch 1: [desriptive statistics](https://towardsdatascience.com/intro-to-descriptive-statistics-252e9c464ac9) ---> To simplify, summarize, and make data sensible(meaningful). 

##### [Tools for Descritive Measurments:](https://help.xlstat.com/s/article/which-descriptive-statistics-tool-should-you-choose?language=en_US)  ![title](stats1.png "tools for Descritive Measurments") 

##### Branch 2: [Inferential statistics](https://medium.com/@rathi.ankit/inferential-statistics-for-data-science-b0075670fc8a) ---> Takes random samples, measure it and tries to pridict or estimate about the population which might not be obvious.

##### [Data Types in Statistics](https://towardsdatascience.com/data-types-in-statistics-347e152e8bee): ..........1.Categorical Data (Nominal, Ordinal) .........2.Numerical Data (Discrete, Continuous, Interval, Ratio)

# in-built statistics

    statistics module:


    Calculating averages
    --------------------
    Function            Description
    ==================  =============================================
    mean                Arithmetic mean (average) of data.
    harmonic_mean       Harmonic mean of data.
    median              Median (middle value) of data.
    median_low          Low median of data.
    median_high         High median of data.
    median_grouped      Median, or 50th percentile, of grouped data.
    mode                Mode (most common value) of data.
    ==================  =============================================
    
    Calculating variability or spread
    ---------------------------------

    ==================  =============================================
    Function            Description
    ==================  =============================================
    pvariance           Population variance of data.
    variance            Sample variance of data.
    pstdev              Population standard deviation of data.
    stdev               Sample standard deviation of data.
    ==================  =============================================


In [2]:
import statistics as st

In [3]:
np.random.seed(0)
arr1=np.random.randint(80, size=10)
arr1

array([44, 47, 64, 67, 67,  9, 21, 36, 70, 12])

In [4]:
st.mean(arr1)               # arithmetic mean (average) of data.

43

In [5]:
st.harmonic_mean(arr1)      # reciprocal of the mean of the reciprocals of all items in the dataset

26.766122521149537

In [6]:
st.median(arr1)             # middle value of numeric data.

45.5

In [7]:
st.median_high(arr1)        # high median of data.

47

In [8]:
st.median_low(arr1)         # low median of numeric data.

44

In [9]:
st.median_grouped(arr1)     # 50th percentile (median) of grouped continuous data.

46.5

In [10]:
st.mode(arr1)               # most common data point from discrete or nominal data.

67

In [11]:
st.pvariance(arr1)          # population variance of data

498

In [12]:
st.variance(arr1)           # sample variance of data

553

In [13]:
st.pstdev(arr1)            # square root of the population variance.

22.315913604421397

In [14]:
st.stdev(arr1)             # square root of the sample variance.

23.515952032609693

#  [numpy stats](https://docs.scipy.org/doc/numpy/reference/routines.statistics.html)

In [15]:
np.mean(arr1)                           # arithmetic mean (average) of data.

43.7

In [16]:
np.median(arr1)                         # middle value of numeric data.

45.5

In [17]:
np.std(arr1)                            # standard deviation

22.325097984107483

In [18]:
np.var(arr1)                            # variance

498.41

In [19]:
arr2=np.random.randint(160, size=16)
arr2

array([ 58,  39,  87,  88,  81,  25,  77,  72,   9, 148, 115,  79,  82,
        99,  29, 147])

In [20]:
arr2=arr2.reshape(4,4)
arr2

array([[ 58,  39,  87,  88],
       [ 81,  25,  77,  72],
       [  9, 148, 115,  79],
       [ 82,  99,  29, 147]])

In [21]:
np.mean(arr2)

77.1875

In [22]:
np.median(arr2)  

80.0

In [23]:
np.std(arr2)  

38.402829892470166

In [24]:
np.var(arr2) 

1474.77734375

In [25]:
np.amin(arr2, axis=0)                      # min value along the row 

array([ 9, 25, 29, 72])

In [26]:
np.amin(arr2, axis=1)                       # min value along the column 

array([39, 25,  9, 29])

In [27]:
np.amax(arr2, axis=0)                       # max value along the row 

array([ 82, 148, 115, 147])

In [28]:
np.amax(arr2, axis=1)                       # max value along the column 

array([ 88,  81, 148, 147])

In [29]:
np.ptp(arr2, axis=0)                        # range along the row 

array([ 73, 123,  86,  75])

In [30]:
np.ptp(arr2, axis=1)                        # range along the column 

array([ 49,  56, 139, 118])

In [31]:
np.cov(arr2)

array([[  567.33333333,   456.        ,  -205.66666667,   -66.66666667],
       [  456.        ,   680.91666667, -1134.75      ,  -274.91666667],
       [ -205.66666667, -1134.75      ,  3550.25      ,  -329.58333333],
       [  -66.66666667,  -274.91666667,  -329.58333333,  2370.91666667]])

##### stack and coveriance(below 3 cells)  ***works on 1-D and same size

In [32]:
Y=np.random.randint(160, size=16).reshape(4,4)    # ***works on 1-D and same size
Y

array([[147, 142,  32,   9],
       [127,  32,  31, 151],
       [114,  28,  34, 128],
       [128,  53, 133,  38]])

In [33]:
X = np.stack((arr2, Y), axis=0)                 # ***works on 1-D and same size
X

array([[[ 58,  39,  87,  88],
        [ 81,  25,  77,  72],
        [  9, 148, 115,  79],
        [ 82,  99,  29, 147]],

       [[147, 142,  32,   9],
        [127,  32,  31, 151],
        [114,  28,  34, 128],
        [128,  53, 133,  38]]])

In [34]:
np.cov(X)                                        # ***works on 1-D and same size

ValueError: m has more than 2 dimensions

#####  ***works on 1-D and same size (below 3 cells)

In [35]:
Y=np.random.randint(160, size=10)
Y

array([ 17,  79, 132, 105,  42,  31, 120,   1,  65,  57])

In [36]:
X = np.stack((arr1, Y), axis=0)
X

array([[ 44,  47,  64,  67,  67,   9,  21,  36,  70,  12],
       [ 17,  79, 132, 105,  42,  31, 120,   1,  65,  57]])

In [37]:
np.cov(X)

array([[ 553.78888889,  273.96666667],
       [ 273.96666667, 1939.87777778]])

In [38]:
np.quantile(arr2, 0.75)

90.75

In [39]:
np.quantile(arr2, 0.5)

80.0

In [40]:
np.quantile(arr2, 0.25)

53.25

In [41]:
 np.percentile(arr2, 75)

90.75

In [42]:
 np.percentile(arr2, 50)

80.0

In [43]:
 np.percentile(arr2, 25)

53.25

In [44]:
 np.percentile(arr2, 10)

27.0

# [pandas stats](https://www.dataquest.io/blog/pandas-cheat-sheet/)

### The pandas library has three data structures:
    1. Series
    2. DataFrame
    3. Panel(Deprecated since version 0.20.0)
    
    
       To represent 3-D data with MultiIndex DataFrame we can use to_frame() method or xarray package method to automate this conversion.)

In [45]:
import pandas as pd

# 1.Series

       A Series is a one-dimensional array, which can hold any type of  data(integers, floats, strings etc.) and Python objects.

### series creation

In [46]:
pd.Series(np.random.randn(5))   # random.randn is part of the NumPy package to generates random numbers

0    1.230291
1    1.202380
2   -0.387327
3   -0.302303
4   -1.048553
dtype: float64

###  index of the series

In [47]:
pd.Series(np.random.randn(5), index=['a','b','c','d','e'])

a   -1.420018
b   -1.706270
c    1.950775
d   -0.509652
e   -0.438074
dtype: float64

### A series can also be derived from a Python dictionary

In [48]:
d = {'A': 10, 'B': 20, 'C': 30}
pd.Series(d)

A    10
B    20
C    30
dtype: int64

# 2.DataFrame

    DataFrame is a 2D data structure.
    Its an analogy to table.
    Can hold different datatypes.
    • A NumPy array
    • Lists
    • Dicts
    • Series
    • A 2D NumPy array

### DataFrame creation using a dictionary of Series

In [49]:
d_series = {'c1': pd.Series(['A', 'B', 'C']), 
     'c2': pd.Series([1, 2., 3., 4.])}
df1 = pd.DataFrame(d_series)
df1

c1   c2
0    A  1.0
1    B  2.0
2    C  3.0
3  NaN  4.0

### DataFrame creation using a dictionary of lists

In [50]:
d_list = {'c1': ['A', 'B', 'C', 'D'],
          'c2': [1, 2.0, 3.0, 4.0]}
df2 = pd.DataFrame(d_list)
df2

c1   c2
0  A  1.0
1  B  2.0
2  C  3.0
3  D  4.0

In [51]:
data = pd.DataFrame({'Country': ['Russia','Colombia','Chile','Equador','Nigeria'],
                    'Rank':[121,40,100,130,11]})
data

Country  Rank
0    Russia   121
1  Colombia    40
2     Chile   100
3   Equador   130
4   Nigeria    11

### describe() quickly analyzes data (descriptive statistics)

In [52]:
data.describe()    

Rank
count    5.000000
mean    80.400000
std     52.300096
min     11.000000
25%     40.000000
50%    100.000000
75%    121.000000
max    130.000000

### info() gives complete information about the data set

In [53]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Country  5 non-null      object
 1   Rank     5 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 208.0+ bytes


# Inserting data

    The pandas library makes it convenient to read data from these formats or to export to these formats.
    • CSV
    • XLS
    • JSON
    • Database

# ....continued with and after ploting(matplotlib, seaborn, plotly)

In [54]:
!nvidia-smi

Thu Mar 26 09:22:14 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 441.87       Driver Version: 441.87       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1050   WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   33C    P8    N/A /  N/A |     77MiB /  4096MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU  