# learning python libraies PART 5
aNAND tIRKEY

In [3]:
import numpy as np
import platform
import pandas as pd
import matplotlib.pylab as plt
print(platform.python_version())
print(np.__version__)
print(pd.__version__)
print(plt.__version__)

3.7.4
1.18.1
1.0.0
1.18.1


In [7]:
np.random.seed(0) #seed sets a value so that same random no is genrated each time code runs
arr1 = np.random.randint(90, size=18) 
arr1

array([44, 47, 64, 67, 67,  9, 83, 21, 36, 87, 70, 88, 88, 12, 58, 65, 39,
       87])

In [12]:
arr1=arr1.reshape(3,6)
arr1

array([[44, 47, 64, 67, 67,  9],
       [83, 21, 36, 87, 70, 88],
       [88, 12, 58, 65, 39, 87]])

# linear algebra essentials

## 1.transpose

In [13]:
arr1.T

array([[44, 83, 88],
       [47, 21, 12],
       [64, 36, 58],
       [67, 87, 65],
       [67, 70, 39],
       [ 9, 88, 87]])

In [14]:
arr1

array([[44, 47, 64, 67, 67,  9],
       [83, 21, 36, 87, 70, 88],
       [88, 12, 58, 65, 39, 87]])

In [17]:
arr1=arr1.T
arr1

array([[44, 83, 88],
       [47, 21, 12],
       [64, 36, 58],
       [67, 87, 65],
       [67, 70, 39],
       [ 9, 88, 87]])

In [18]:
arr1

array([[44, 83, 88],
       [47, 21, 12],
       [64, 36, 58],
       [67, 87, 65],
       [67, 70, 39],
       [ 9, 88, 87]])

## 2. inverse of matrix

In [19]:
np.linalg.inv(arr1)      # error because trying to find inverse of matrix for non-square matrix.

LinAlgError: Last 2 dimensions of the array must be square

In [21]:
square_matrix=np.random.randint(90, size=16)
square_matrix

array([46, 88, 81, 37, 25, 77, 72,  9, 20, 80, 69, 79, 47, 64, 82, 88])

In [22]:
square_matrix=square_matrix.reshape(4,4)
square_matrix

array([[46, 88, 81, 37],
       [25, 77, 72,  9],
       [20, 80, 69, 79],
       [47, 64, 82, 88]])

In [24]:
inverse_matrix=np.linalg.inv(square_matrix)
inverse_matrix

array([[ 0.05364753, -0.04057992, -0.01855524, -0.00174858],
       [ 0.04021087, -0.0277937 ,  0.02225166, -0.03404023],
       [-0.06156468,  0.05938397, -0.01875449,  0.03664821],
       [-0.00052984, -0.01344809,  0.01120293,  0.00290461]])

## 3. determinant of matrix

In [26]:
np.linalg.det(square_matrix)

-2885761.999999997

##### The determinant only exists for square matrices

In [28]:
np.linalg.det(arr1)     #The determinant only exists for square matrices

LinAlgError: Last 2 dimensions of the array must be square

## 4. rank of matrix

##### note:
#####  The rank of a matrix is the maximum number of independent rows (or, the maximum number of independent columns). 
#####  A square matrix An×n is non-singular only if its rank is equal to n.
#####  When the rank equals the smallest dimension it is called "full rank", a smaller rank is called "rank deficient".

In [29]:
np.linalg.matrix_rank(square_matrix)

4

In [30]:
np.linalg.matrix_rank(arr1)

3

## 5. finding diagonal of matrix

In [33]:
arr1

array([[44, 83, 88],
       [47, 21, 12],
       [64, 36, 58],
       [67, 87, 65],
       [67, 70, 39],
       [ 9, 88, 87]])

In [35]:
print(arr1.diagonal())

[44 21 58]


In [37]:
arr1=arr1.T
arr1

array([[44, 47, 64, 67, 67,  9],
       [83, 21, 36, 87, 70, 88],
       [88, 12, 58, 65, 39, 87]])

In [38]:
print(arr1.diagonal())

[44 21 58]


In [46]:
print(square_matrix)
print("\n \n diagonal :",square_matrix.diagonal())

[[46 88 81 37]
 [25 77 72  9]
 [20 80 69 79]
 [47 64 82 88]]

 
 diagonal : [46 77 69 88]


In [47]:
#Print the diagonal one above the Principal diagonal
print(square_matrix.diagonal(offset=1))

[88 72 79]


In [48]:
print(square_matrix.diagonal(offset=2))

[81  9]


In [51]:
#Print the diagonal one below Principal diagonal
print(square_matrix.diagonal(offset=-1))

[25 80 82]


In [50]:
print(square_matrix.diagonal(offset=-2))

[20 64]


## 6. eigen value and  eigen vectors

##### note: 
##### Eigenvectors are widely used in Machine Learning libraries.
##### Eigenvectors are vectors that when that transformation is applied, change only in scale(not direction)

In [54]:
eigen_values ,eigen_vectors=np.linalg.eig(square_matrix)  #returns two values ...1st eigenvalue and 2nd eigenvector

In [55]:
eigen_values

array([234.74908064, -14.89535524,  21.17902806,  38.96724654])

In [56]:
eigen_vectors

array([[-0.50163992,  0.07470063, -0.7436433 , -0.5018447 ],
       [-0.34898997,  0.5703933 , -0.36011553, -0.55144575],
       [-0.51533944, -0.78336776,  0.50662065,  0.39881042],
       [-0.60082331,  0.23538531,  0.24626603,  0.53386303]])

In [57]:
eigen_values1 ,eigen_vectors2 =np.linalg.eig(inverse_matrix)

In [58]:
eigen_values1

array([-0.06713502,  0.04721652,  0.02566258,  0.00425987])

In [59]:
eigen_vectors2

array([[-0.07470063, -0.7436433 , -0.5018447 , -0.50163992],
       [-0.5703933 , -0.36011553, -0.55144575, -0.34898997],
       [ 0.78336776,  0.50662065,  0.39881042, -0.51533944],
       [-0.23538531,  0.24626603,  0.53386303, -0.60082331]])

## 7. solve linear equations

##### 4x  + 3y = 20
##### -5x + 9y = 26

### 7.1 method 1

In [67]:
A = np.array([4,3,-5,9])
A

array([ 4,  3, -5,  9])

In [69]:
A=A.reshape(2,2)
A

array([[ 4,  3],
       [-5,  9]])

In [71]:
inv_A = np.linalg.inv(A)
inv_A

array([[ 0.17647059, -0.05882353],
       [ 0.09803922,  0.07843137]])

In [72]:
B = np.array([20, 26])
solved =np.linalg.inv(A).dot(B)
solved

array([2., 4.])

### 7.2 method 2 using "solve"

In [73]:
solved2 = np.linalg.solve(A,B)
solved2

array([2., 4.])

    Functions present in numpy.linalg are listed below.

    
    Matrix and vector products
    --------------------------

       multi_dot
       matrix_power

    Decompositions
    --------------
    
       cholesky
       qr
       svd

    Matrix eigenvalues
    ------------------

       eig
       eigh
       eigvals
       eigvalsh

    Norms and other numbers
    -----------------------

       norm
       cond
       det
       matrix_rank
       slogdet

    Solving equations and inverting matrices
    ----------------------------------------

       solve
       tensorsolve
       lstsq
       inv
       pinv
       tensorinv

    Exceptions
    ----------
    
       LinAlgError

In [74]:
!nvidia-smi

Tue Mar 17 19:16:16 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 441.87       Driver Version: 441.87       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1050   WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   41C    P8    N/A /  N/A |     77MiB /  4096MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU  