# learning python libraies PART 2
aNAND tIRKEY

In [121]:
import numpy as np
import platform
print(platform.python_version())
print(np.__version__)

3.7.4
1.18.1


In [122]:
np.random.seed(0)  #seed sets a value so that same random no is genrated each time code runs

In [123]:
arr1 = np.random.randint(10, size=6) # 1-D array and stop value at 10 default sart is 0
arr1

array([5, 0, 3, 3, 7, 9])

In [124]:
arr2 = np.random.randint(10, size=(3, 4)) # 2-D arrayand stop value at 10 default sart is 0
arr2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [125]:
arr3 = np.random.randint(10, size=(3, 4, 5)) # 3-D arrayand stop value at 10 default sart is 0
arr3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

### Array Attributes

    Each array has attributes 
    "ndim"      --> (dimensions 1d,2d,3d....etc ), 
    "shape"     --> (the size of each dimension), 
    "size"      --> (the total size of the array)
    "dtype"     --> (data type held by array)
    "itemsize"  --> (size of each elements of an array)
    "nbytes"    --> (total size of array in bytes)

In [126]:
print("arr1 ndim: ", arr1.ndim)
print("arr1 shape:", arr1.shape)
print("arr1 size: ", arr1.size)
print("dtype:", arr1.dtype)
print("itemsize:", arr1.itemsize, "bytes")
print("nbytes:", arr1.nbytes, "bytes")

arr1 ndim:  1
arr1 shape: (6,)
arr1 size:  6
dtype: int32
itemsize: 4 bytes
nbytes: 24 bytes


In [127]:
print("arr2 ndim: ", arr2.ndim)
print("arr2 shape:", arr2.shape)
print("arr2 size: ", arr2.size)
print("dtype:", arr2.dtype)
print("itemsize:", arr2.itemsize, "bytes")
print("nbytes:", arr2.nbytes, "bytes")

arr2 ndim:  2
arr2 shape: (3, 4)
arr2 size:  12
dtype: int32
itemsize: 4 bytes
nbytes: 48 bytes


In [128]:
print("arr3 ndim: ", arr3.ndim)
print("arr3 shape:", arr3.shape)
print("arr3 size: ", arr3.size)
print("dtype:", arr3.dtype)
print("itemsize:", arr3.itemsize, "bytes")
print("nbytes:", arr3.nbytes, "bytes")

arr3 ndim:  3
arr3 shape: (3, 4, 5)
arr3 size:  60
dtype: int32
itemsize: 4 bytes
nbytes: 240 bytes


# mathematical operations

## 1.Array subtraction

In [129]:
arr4=np.random.randint(30,size=(3,4))
arr4

array([[15, 20,  3, 12],
       [ 4, 20,  8, 14],
       [15, 20,  3, 26]])

In [130]:
arr5=np.random.randint(30,size=(3,4))
arr5

array([[23, 15, 13, 21],
       [21, 16, 17,  5],
       [ 9,  3,  0,  5]])

In [131]:
arr6=arr5-arr4
arr6

array([[  8,  -5,  10,   9],
       [ 17,  -4,   9,  -9],
       [ -6, -17,  -3, -21]])

In [132]:
arr7=np.random.randint(30,size=(3,7))
arr7

array([[ 0, 17, 18,  4,  2, 16, 29],
       [ 3,  2, 10, 13, 16,  7, 21],
       [ 9,  0, 10, 18, 11, 26, 23]])

In [133]:
arr8=arr5-arr7    #shape of array are diifrent therfore cannot be subtracted

ValueError: operands could not be broadcast together with shapes (3,4) (3,7) 

In [134]:
arr8=arr7-arr7
arr8

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

## 2.array squaring

In [135]:
arr7**2   # ** means power 

array([[  0, 289, 324,  16,   4, 256, 841],
       [  9,   4, 100, 169, 256,  49, 441],
       [ 81,   0, 100, 324, 121, 676, 529]], dtype=int32)

## 3.array cubing

In [136]:
arr7**3   #

array([[    0,  4913,  5832,    64,     8,  4096, 24389],
       [   27,     8,  1000,  2197,  4096,   343,  9261],
       [  729,     0,  1000,  5832,  1331, 17576, 12167]], dtype=int32)

## 4.adding  array

In [137]:
arr8    #array is empty after substraction

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [138]:
arr8=arr4+arr5+arr6    #using empty array to put values
arr8

array([[46, 30, 26, 42],
       [42, 32, 34, 10],
       [18,  6,  0, 10]])

In [139]:
arr8=arr8-arr8
arr8

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [140]:
arr8=arr4+arr5+arr6-0.3    #we can also operate with scaler values and scaler fractional values.
arr8

array([[45.7, 29.7, 25.7, 41.7],
       [41.7, 31.7, 33.7,  9.7],
       [17.7,  5.7, -0.3,  9.7]])

## 5.trignometric function

In [141]:
np.cos(arr8)

array([[-0.14637868, -0.14462127,  0.84337707, -0.6529712 ],
       [-0.6529712 ,  0.95992174, -0.65431552, -0.96236488],
       [ 0.40889274,  0.83471278,  0.95533649, -0.96236488]])

## 6.conditional operator

In [142]:
arr8<20

array([[False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True]])

In [143]:
arr8<=arr7   #error because the have diffrent shape

ValueError: operands could not be broadcast together with shapes (3,4) (3,7) 

In [144]:
arr4<=arr6   #each element is compared with its respective place of other array 

array([[False, False,  True, False],
       [ True, False,  True, False],
       [False, False, False, False]])

## 7.matrix multiplication

In [145]:
arr4*arr5

array([[345, 300,  39, 252],
       [ 84, 320, 136,  70],
       [135,  60,   0, 130]])

## 8.dot product

In [146]:
A1 = np.array([[1, 1],[0, 1]])
A2 = np.array([[2, 0],[3, 4]])
np.dot(A1, A2)

array([[5, 4],
       [3, 4]])

In [147]:
np.dot(arr4, arr5)   #The column of the first matrix and the row of the second matrix should be equal.

ValueError: shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

In [148]:
arr9=np.random.randint(30,size=(4,3))
arr9

array([[27,  2, 25],
       [ 2,  3, 27],
       [ 3, 18, 14],
       [ 3, 20, 17]])

In [149]:
np.dot(arr4, arr9)

array([[ 490,  384, 1161],
       [ 214,  492,  990],
       [ 532,  664, 1399]])

# Reshape

In [152]:
#or reshape arr5
arr5=np.reshape(arr5,(4,3))
arr5

array([[23, 15, 13],
       [21, 21, 16],
       [17,  5,  9],
       [ 3,  0,  5]])

In [153]:
np.dot(arr4, arr5)

array([[852, 660, 602],
       [690, 520, 514],
       [894, 660, 672]])

In [154]:
np.arange(1, 15)   #arange ends before limit

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [155]:
arr10 = np.arange(1, 15).reshape((2, 7))    #total elements eqauls mutiple 7*2=14
print(arr10)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [156]:
np.reshape(arr10,(7,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14]])

In [157]:
arr11 = np.arange(1, 31).reshape((3, 10))   #3*10=30
print(arr11)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]


In [158]:
np.reshape(arr11,(6,5))    #6*5=30

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [159]:
np.reshape(arr11,(2,15))   #2*15=30

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

#  continued in part3

In [160]:
!nvidia-smi

Fri Mar 06 00:27:16 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 441.87       Driver Version: 441.87       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1050   WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   39C    P8    N/A /  N/A |     77MiB /  4096MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU  